### ISSUE TITLE
报错 thread 'main' panicked at 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by soapffz** [360quake/quake_rs#14]
使用搜索时报错thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/quake.rs:276:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

![image](https://user-images.githubusercontent.com/43143519/190836201-3625197d-164e-4728-a856-15c5b5c6d5cd.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version: 2.1和2.2版本均出现报错

**Comment by rootphantomer** [comment]
windows下也报错，看报错行数，目测是解析response的时候出了问题，先用quake_go代替下。工作日，我去抓个包。

**Comment by rootphantomer** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/6481352/190939088-1b0281b3-a3c8-44f7-9a6d-f86c23501266.png">

重新编译了一个版本，本地测试没有问题。
