### ISSUE TITLE
win下AND语法无法使用

### ISSUE THREAD

**Issue by getcode2git** [360quake/quake_rs#2]
error: Found argument 'AND' which wasn't expected, or isn't valid in this context

**Comment by imjdl** [comment]
> error: Found argument 'AND' which wasn't expected, or isn't valid in this context

windows 下 语法需要使用双引号括起来，如：quake search "port:80 AND ip:112.74.107.2/24"  或者 quake search "app:\"Jumpserver堡垒机\""
