### ISSUE TITLE
可否添加一个批量查询的功能

### ISSUE THREAD

**Issue by F6JO** [360quake/quake_rs#5]

**Comment by rootphantomer** [comment]
批量查询具体指的是？？

**Comment by F6JO** [comment]
比如我在txt里每行放了一个语句，可以读取txt并查询里面每一条语句统一返回结果


忠厚老实的阿岩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "360quake/quake_rs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [360quake/quake_rs] 可否添加一个批量查询的功能 (Issue #5)





 
批量查询具体指的是？？

**Comment by rootphantomer** [comment]
那结果输出是以什么形式输出？也是要存到不同的txt里还是？

**Comment by F6JO** [comment]
类似fofax那种，是合并输出

**Comment by rootphantomer** [comment]
那实际上，txt里面如果是
```txt
app:"xxx"
app:"qqq"
```
输出的结果集和 
```
app:"xxx" OR app:"qqq"
```
一直的咯

**Comment by rootphantomer** [comment]
> 类似fofax那种，是合并输出

https://github.com/360quake/quake_go  quake_go工具已经先支持，./quake search -qt ./test.txt，quake_rs后续支持。

**Comment by rootphantomer** [comment]
> 那实际上，txt里面如果是
> 
> ```
> app:"xxx"
> app:"qqq"
> ```
> 
> 输出的结果集和
> 
> ```
> app:"xxx" OR app:"qqq"
> ```
> 
> 一致的咯

v2.2新增./quake file ./test.txt 的功能支持该需求
